### ISSUE TITLE
Operators are getting duplicate names?

### ISSUE THREAD

**Issue by PhpSriptKiddie** [sdrdis/jquery.flowchart#20]
Hey there.

When adding new operators by dragging them into the chart, they don't seem to consider which operators are already present. So, if I make a blank chart and add three operators, these are called op_0, op_1 and op_2. 

But if I save the data and load it again, the names of the new operators are once again starting from 0 even though this already exists, which makes some weird behaviour. The same happens if I'm starting out with operators name op_0 and op_1. 

How can I make new operators consider the already existing ones?

**Comment by sdrdis** [comment]
Hi,

Sorry for my late answer. As I understand, you adapted the last example so that you can load custom data too. Though I did not code it with that feature in mind, I changed the code so that the next person who does this doesn't have the same problem.

The best thing to do, if you don't care about the ID, is to go through the `addOperator` method that handles ids for you. If you absolutely want to control the ids, you can use the `doesOperatorExists` method I added few minutes ago to check whether or not an operator with the same ID already exists...

Thanks,
